[package]
name = "pcf85263"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
embedded-hal = "1.0"
rtcc = "0.3.2"

[dev-dependencies]
embedded-hal-mock = "0.11"
